{"name": "Проверка, что система возвращает ошибку при авторизации под несуществующим пользователем. POST /api/v1/courier/login", "status": "passed", "start": 1759660376729, "stop": 1759660377184, "uuid": "b9ed443a-9afb-4a1a-aaee-a43efcc54b63", "historyId": "4c13dcb080e3ce7662c7cb37e55ba323", "testCaseId": "4c13dcb080e3ce7662c7cb37e55ba323", "fullName": "tests.test_login_courier.TestsCourierLogin#test_login_nonexistent_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login_courier"}, {"name": "subSuite", "value": "TestsCourierLogin"}, {"name": "host", "value": "Natalias-MacBook-Air.local"}, {"name": "thread", "value": "35525-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login_courier"}], "titlePath": ["tests", "test_login_courier.py", "TestsCourierLogin"]}